export const MAX_SEQUENCES = 5000;

export const DNA_MODELS = [
  { value: "GTR", label: "GTR" },
  { value: "TN93", label: "TN93" },
  { value: "HKY85", label: "HKY85" },
  { value: "F84", label: "F84" },
  { value: "F81", label: "F81" },
  { value: "K80", label: "K80" },
  { value: "JC69", label: "JC69" },
] as const;

export const PROTEIN_MODELS = [
  { value: "LG", label: "LG" },
  { value: "WAG", label: "WAG" },
  { value: "JTT", label: "JTT" },
  { value: "Blosum62", label: "Blosum62" },
  { value: "Dayhoff", label: "Dayhoff" },
  { value: "HIVw", label: "HIVw" },
  { value: "HIVb", label: "HIVb" },
] as const;

export const THRESHOLD_OPTIONS = [
  "0",
  "0.1",
  "0.2",
  "0.3",
  "0.4",
  "0.5",
  "0.6",
  "0.7",
  "0.8",
  "0.9",
  "1.0",
] as const;

export const DEFAULT_METADATA_FIELDS = [
  { id: "genome_id", name: "Genome ID", selected: true },
  { id: "genome_name", name: "Genome Name", selected: true },
  { id: "species", name: "Species", selected: true },
  { id: "strain", name: "Strain", selected: true },
  { id: "accession", name: "Accession", selected: true },
  { id: "subtype", name: "Subtype", selected: true },
];

export const BASE_METADATA_OPTIONS = [
  { value: "genome_name", label: "Genome Name" },
  { value: "genome_length", label: "Genome Length" },
  { value: "feature_group", label: "Feature Group" },
  { value: "species", label: "Species" },
  { value: "strain", label: "Strain" },
  { value: "accession", label: "Accession" },
  { value: "subtype", label: "Subtype" },
  { value: "lineage", label: "Lineage" },
  { value: "host_group", label: "Host Group" },
  { value: "host_common_name", label: "Host Common Name" },
  { value: "collection_date", label: "Collection Date" },
  { value: "collection_year", label: "Collection Year" },
  { value: "geographic_group", label: "Geographic Group" },
  { value: "isolation_country", label: "Isolation Country" },
  { value: "geographic_location", label: "Geographic Location" },
  { value: "more_options", label: "... More Options ..." },
];

export const GENOME_ADVANCED_FIELDS: string[] = [
  "public",
  "genome_id",
  "genome_name",
  "other_name",
  "taxon_id",
  "taxon_lineage_ids",
  "taxon_lineage_names",
  "superkingdom",
  "kingdom",
  "phylum",
  "class",
  "order",
  "family",
  "genus",
  "species",
  "genome_status",
  "strain",
  "serovar",
  "biovar",
  "pathovar",
  "mlst",
  "segment",
  "subtype",
  "h_type",
  "n_type",
  "h1_clade_global",
  "h1_clade_us",
  "h3_clade",
  "h5_clade",
  "ph1n1_like",
  "lineage",
  "clade",
  "subclade",
  "other_typing",
  "culture_collection",
  "type_strain",
  "reference_genome",
  "completion_date",
  "publication",
  "authors",
  "bioproject_accession",
  "biosample_accession",
  "assembly_accession",
  "sra_accession",
  "genbank_accessions",
  "sequencing_centers",
  "sequencing_platform",
  "sequencing_depth",
  "assembly_method",
  "chromosomes",
  "plasmids",
  "contigs",
  "genome_length",
  "gc_content",
  "contig_l50",
  "contig_n50",
  "coarse_consistency",
  "fine_consistency",
  "checkm_completeness",
  "checkm_contamination",
  "genome_quality_flags",
  "genome_quality",
  "nearest_genomes",
  "outgroup_genomes",
  "isolation_source",
  "isolation_comments",
  "collection_date",
  "collection_year",
  "season",
  "isolation_country",
  "state_province",
  "geographic_group",
  "geographic_location",
  "host_name",
  "host_common_name",
  "host_gender",
  "host_age",
  "host_health",
  "host_group",
  "lab_host",
  "passage",
  "other_clinical",
  "additional_metadata",
  "comments",
  "date_inserted",
  "date_modified",
];

