packages:
  - .
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
- next
- react
- react-dom
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
patchedDependencies:
  molstar: patches/molstar.patch
