packages:
  - .
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  core-js: false
  ejs: false
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  styled-components: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - archaeopteryx@2.3.2
patchedDependencies:
  archaeopteryx@2.3.2: patches/archaeopteryx@2.3.2.patch
  molstar: patches/molstar.patch
  phyloxml@1.0.0: patches/phyloxml@1.0.0.patch
