import type { BaselineMap } from "./baseline";

// Auto-generated by `pnpm a11y:baseline:update`. Do not edit manually.
// Bump maxNodes only with a linked ticket. Critical violations may never be added here.
//
// The "*" wildcard route applies to all routes lacking a more-specific entry.
const generatedBaseline: BaselineMap = {
  "*": {
    "dxkb-light": {
      // WebKit-only: axe flags Base UI's internal focus-guard <span> elements
      // (data-base-ui-focus-guard) as ARIA commands without names. The spans are
      // rendered by @base-ui/react Dialog/Command and are not author-controlled.
      // Track removal once Base UI adds aria-hidden / role="none" to focus guards.
      // Ticket: DXKBCORE-133 — maxNodes normalized by generator in Phase 2.
      "aria-command-name": { maxNodes: 99, ticket: "DXKBCORE-133" },
    },
    "dxkb-dark": {
      "aria-command-name": { maxNodes: 99, ticket: "DXKBCORE-133" },
    },
  },
};

export default generatedBaseline;
