import type { BaselineMap, ReflowSkipMap } from "./baseline";

// Auto-generated by `pnpm a11y:baseline:update`. Do not edit manually.
// Bump maxNodes only with a linked ticket. Critical violations may never be added here.
//
// The "*" wildcard route applies to all routes lacking a more-specific entry.
const generatedBaseline: BaselineMap = {
  "*": {
    "dxkb-light": {
      // WebKit-only: axe flags Base UI's internal focus-guard <span> elements
      // (data-base-ui-focus-guard) as ARIA commands without names. The spans are
      // rendered by @base-ui/react Dialog/Command and are not author-controlled.
      // Track removal once Base UI adds aria-hidden / role="none" to focus guards.
      // Ticket: DXKBCORE-133 — maxNodes normalized by generator in Phase 2.
      "aria-command-name": { maxNodes: 99, ticket: "DXKBCORE-133" },
      // Design-system color token values in some light-theme components do not meet
      // 4.5:1 contrast ratio. Tracked for a dedicated design-token audit pass.
      // Ticket: DXKBCORE-174 — calibrated to observed max of 71 nodes (organisms-viruses).
      "color-contrast": { maxNodes: 75, ticket: "DXKBCORE-174" },
      // SVG circular icons on organisms pages lack <title> / role="img".
      // Ticket: DXKBCORE-175 — calibrated to observed max of 48 nodes (organisms-bacteria).
      "svg-img-alt": { maxNodes: 50, ticket: "DXKBCORE-175" },
      // Switches / toggle fields rendered via Base UI lack explicit label
      // association when used without a wrapping <label>. Ticket: DXKBCORE-176
      "aria-toggle-field-name": { maxNodes: 10, ticket: "DXKBCORE-176" },
    },
    "dxkb-dark": {
      "aria-command-name": { maxNodes: 99, ticket: "DXKBCORE-133" },
      // Dark-theme CSS variables produce insufficient contrast ratios across
      // multiple surfaces (navbar, tabs, badges, cards). Tracked for a
      // dark-theme contrast audit. Ticket: DXKBCORE-174 — calibrated to observed max of 74 (taxonomy/virus).
      "color-contrast": { maxNodes: 80, ticket: "DXKBCORE-174" },
      // SVG circular icons on organisms pages lack <title> / role="img" in dark theme too.
      // Ticket: DXKBCORE-175 — calibrated to observed max of 48 nodes (same as light).
      "svg-img-alt": { maxNodes: 50, ticket: "DXKBCORE-175" },
      // Same switch/toggle issue as light theme — Base UI Checkbox/Switch
      // root span receives no htmlFor association in dark theme scans.
      "aria-toggle-field-name": { maxNodes: 10, ticket: "DXKBCORE-176" },
      // taxonomy/bacteria mock error causes missing lang and title in dark theme.
      "document-title": { maxNodes: 1, ticket: "DXKBCORE-177" },
      "html-has-lang": { maxNodes: 1, ticket: "DXKBCORE-177" },
    },
  },
  // organisms-viruses dark has more color-contrast nodes than the wildcard cap (106 vs 80)
  // because the viruses page lists many family-level links grouped by genome type.
  // Ticket: DXKBCORE-174 — calibrated to 106 nodes.
  "organisms-viruses": {
    "dxkb-dark": {
      "color-contrast": { maxNodes: 110, ticket: "DXKBCORE-174" },
    },
  },
  // taxonomy/virus dark exceeds the wildcard 80-node cap (94 observed) because the
  // AMR chart legend pills and view-tab search components add dark-mode contrast nodes
  // beyond what existed before the merge. Ticket: DXKBCORE-174
  "taxonomy/virus": {
    "dxkb-dark": {
      "color-contrast": { maxNodes: 100, ticket: "DXKBCORE-174" },
    },
  },
  // taxonomy/bacteria renders an error page when mock data lacks taxon_name,
  // causing missing <title> and missing html[lang]. Ticket: DXKBCORE-177
  "taxonomy/bacteria": {
    "dxkb-light": {
      "document-title": { maxNodes: 1, ticket: "DXKBCORE-177" },
      "html-has-lang": { maxNodes: 1, ticket: "DXKBCORE-177" },
    },
  },
};

// Routes with pre-existing WCAG 1.4.10 reflow failures at 320px viewport width.
// These are structural/layout issues requiring dedicated CSS fixes.
// Ticket: DXKBCORE-178
export const reflowSkip: ReflowSkipMap = {
  home: { ticket: "DXKBCORE-178" },
  "sign-in": { ticket: "DXKBCORE-178" },
  "sign-up": { ticket: "DXKBCORE-178" },
  "forgot-password": { ticket: "DXKBCORE-178" },
  about: { ticket: "DXKBCORE-178" },
  citations: { ticket: "DXKBCORE-178" },
  contact: { ticket: "DXKBCORE-178" },
  faq: { ticket: "DXKBCORE-178" },
  funding: { ticket: "DXKBCORE-178" },
  help: { ticket: "DXKBCORE-178" },
  news: { ticket: "DXKBCORE-178" },
  publications: { ticket: "DXKBCORE-178" },
  "privacy-policy": { ticket: "DXKBCORE-178" },
  "related-resources": { ticket: "DXKBCORE-178" },
  team: { ticket: "DXKBCORE-178" },
  updates: { ticket: "DXKBCORE-178" },
  search: { ticket: "DXKBCORE-178" },
  "taxonomy/virus": { ticket: "DXKBCORE-178" },
  "organisms-all": { ticket: "DXKBCORE-178" },
  "organisms-bacteria": { ticket: "DXKBCORE-178" },
  "organisms-viruses": { ticket: "DXKBCORE-178" },
  // View list pages — mobile navbar overflows at 320px, same root cause as above.
  "taxonomy-list": { ticket: "DXKBCORE-178" },
  "genome-list": { ticket: "DXKBCORE-178" },
  "feature-list": { ticket: "DXKBCORE-178" },
  "epitope-list": { ticket: "DXKBCORE-178" },
  "surveillance-list": { ticket: "DXKBCORE-178" },
  "serology-list": { ticket: "DXKBCORE-178" },
  // View singular pages — same mobile navbar overflow root cause.
  genome: { ticket: "DXKBCORE-178" },
  feature: { ticket: "DXKBCORE-178" },
  epitope: { ticket: "DXKBCORE-178" },
  surveillance: { ticket: "DXKBCORE-178" },
  serology: { ticket: "DXKBCORE-178" },
  "experiment-singular": { ticket: "DXKBCORE-178" },
  "strain-list": { ticket: "DXKBCORE-178" },
  "domains-and-motifs": { ticket: "DXKBCORE-178" },
  experiment: { ticket: "DXKBCORE-178" },
  "protein-structure": { ticket: "DXKBCORE-178" },
};

// ── Warn-tier tracking (DoD item 6) ──────────────────────────────────────────
// These rule IDs were observed in warn-tier (best-practice / WCAG 2.2 AA) during
// the first real sweep. All are tracked under DXKBCORE-174; the report artifact
// (a11y-report/a11y-summary.json) enumerates every instance per route/theme.
//
// Rule IDs → brief description → ticket:
//   heading-order              — Heading levels should only increase by one        → DXKBCORE-174
//   landmark-main-is-top-level — Main landmark inside another landmark             → DXKBCORE-174
//   landmark-no-duplicate-main — More than one main landmark                       → DXKBCORE-174
//   landmark-one-main          — Document should have exactly one main landmark    → DXKBCORE-174
//   landmark-unique            — Landmarks must have unique role/label combos      → DXKBCORE-174
//   page-has-heading-one       — Page should contain a level-one heading           → DXKBCORE-174
//   region                     — All page content should be within landmarks       → DXKBCORE-174
//   label-title-only           — Form elements should have a visible label         → DXKBCORE-174
//   target-size                — Touch targets must be ≥24px (WCAG 2.2 AA)         → DXKBCORE-174
export default generatedBaseline;
