import type { DataFieldMap } from "./types";

export const ppiFields = {
  id: {
    label: "ID",
    field: "id",
    hidden: true,
    group: "Other",
    search: true,
  },
  genome_id_a: {
    label: "Genome ID A",
    field: "genome_id_a",
    hidden: true,
    group: "Interactor A",
    search: true,
  },
  genome_name_a: {
    label: "Genome Name A",
    field: "genome_name_a",
    hidden: true,
    group: "Interactor A",
    search: true,
  },
  interactor_a: {
    label: "Interactor A",
    field: "interactor_a",
    hidden: false,
    group: "Interactor A",
    search: true,
  },
  interactor_type_a: {
    label: "Interactor Type A",
    field: "interactor_type_a",
    hidden: true,
    group: "Interactor A",
    search: true,
  },
  feature_id_a: {
    label: "Feature ID A",
    field: "feature_id_a",
    hidden: true,
    group: "Interactor A",
    search: true,
  },
  refseq_locus_tag_a: {
    label: "RefSeq Locus Tag A",
    field: "refseq_locus_tag_a",
    hidden: true,
    group: "Interactor A",
    search: true,
  },
  gene_a: {
    label: "Gene A",
    field: "gene_a",
    hidden: false,
    group: "Interactor A",
    search: true,
  },
  interactor_desc_a: {
    label: "Desc A",
    field: "interactor_desc_a",
    hidden: false,
    group: "Interactor A",
    search: true,
  },
  taxon_id_a: {
    label: "Taxon ID A",
    field: "taxon_id_a",
    hidden: true,
    group: "Interactor A",
    search: true,
  },
  genome_id_b: {
    label: "Genome ID B",
    field: "genome_id_b",
    hidden: true,
    group: "Interactor B",
    search: true,
  },
  genome_name_b: {
    label: "Genome Name B",
    field: "genome_name_b",
    hidden: true,
    group: "Interactor B",
    search: true,
  },
  interactor_b: {
    label: "Interactor B",
    field: "interactor_b",
    hidden: false,
    group: "Interactor B",
    search: true,
  },
  interactor_type_b: {
    label: "Interactor Type B",
    field: "interactor_type_b",
    hidden: true,
    group: "Interactor B",
    search: true,
  },
  feature_id_b: {
    label: "Feature ID B",
    field: "feature_id_b",
    hidden: true,
    group: "Interactor B",
    search: true,
  },
  refseq_locus_tag_b: {
    label: "RefSeq Locus Tag B",
    field: "refseq_locus_tag_b",
    hidden: true,
    group: "Interactor B",
    search: true,
  },
  gene_b: {
    label: "Gene B",
    field: "gene_b",
    hidden: false,
    group: "Interactor B",
    search: true,
  },
  interactor_desc_b: {
    label: "Desc B",
    field: "interactor_desc_b",
    hidden: false,
    group: "Interactor B",
    search: true,
  },
  taxon_id_b: {
    label: "Taxon ID B",
    field: "taxon_id_b",
    hidden: true,
    group: "Interactor B",
    search: true,
  },
  category: {
    label: "Category",
    field: "category",
    hidden: false,
    group: "Interaction",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  interaction_type: {
    label: "Interaction Type",
    field: "interaction_type",
    hidden: false,
    group: "Interaction",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  detection_method: {
    label: "Detection Method",
    field: "detection_method",
    hidden: false,
    group: "Interaction",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  evidence: {
    label: "Evidence",
    field: "evidence",
    hidden: false,
    group: "Interaction",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  pubmed: {
    label: "Pubmed",
    field: "pubmed",
    hidden: true,
    group: "Interaction",
    search: true,
  },
  score: {
    label: "Score",
    field: "score",
    hidden: true,
    group: "Interaction",
    search: true,
  },
  source_db: {
    label: "Source DB",
    field: "source_db",
    hidden: true,
    group: "Other",
    search: true,
  },
  domain_a: {
    label: "Domain A",
    field: "domain_a",
    hidden: true,
    group: "Other",
    search: true,
  },
  domain_b: {
    label: "Domain B",
    field: "domain_b",
    hidden: true,
    group: "Other",
    search: true,
  },
  date_inserted: {
    label: "Date Inserted",
    field: "date_inserted",
    hidden: true,
    group: "Other",
    search: true,
  },
  date_modified: {
    label: "Date Modified",
    field: "date_modified",
    hidden: true,
    group: "Other",
    search: true,
  },
} satisfies DataFieldMap;
