import type { DataFieldMap } from "./types";

// Sequence Features (SFVT tab). This is the `sequence_feature` core — one row
// per feature, scoped by taxon_id (see the SFVT view factory). NOT the
// `sequence_feature_vt` core, which stores one row per variant-type occurrence
// (~2.2M rows, no taxon field) and inflated the tab count 350x.
// Columns mirror legacy SFVTGrid.
export const sequenceFeatureFields = {
  sf_name: {
    label: "Sequence Feature (SF) Name",
    field: "sf_name",
    hidden: false,
    group: "Sequence Feature",
    facet: false,
    facet_hidden: true,
    search: true,
  },
  sf_id: {
    label: "Sequence Feature (SF) Identifier",
    field: "sf_id",
    hidden: false,
    group: "Sequence Feature",
    facet: false,
    facet_hidden: true,
    search: true,
  },
  gene: {
    label: "Gene",
    field: "gene",
    hidden: false,
    group: "Sequence Feature",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  length: {
    label: "SF Length",
    field: "length",
    hidden: false,
    group: "Sequence Feature",
    facet: false,
    facet_hidden: true,
    search: false,
  },
  variant_types: {
    label: "Variant Types",
    field: "variant_types",
    hidden: false,
    group: "Variant Type",
    facet: false,
    facet_hidden: true,
    search: false,
  },
  sf_category: {
    label: "SF Category",
    field: "sf_category",
    hidden: false,
    group: "Sequence Feature",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  segments: {
    label: "Reference Positions",
    field: "segments",
    hidden: false,
    group: "Sequence Feature",
    facet: false,
    facet_hidden: true,
    search: false,
  },
  source_strain: {
    label: "Source Strain",
    field: "source_strain",
    hidden: false,
    group: "Sequence Feature",
    facet: false,
    facet_hidden: true,
    search: true,
  },
  product: {
    label: "Product",
    field: "product",
    hidden: false,
    group: "Sequence Feature",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  evidence_code: {
    label: "Evidence Code",
    field: "evidence_code",
    hidden: true,
    group: "Sequence Feature",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  source: {
    label: "Source",
    field: "source",
    hidden: true,
    group: "Sequence Feature",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  additional_metadata: {
    label: "Additional Metadata",
    field: "additional_metadata",
    hidden: true,
    group: "Sequence Feature",
    facet: true,
    facet_hidden: false,
    search: true,
  },
  segment: {
    label: "Segment",
    field: "segment",
    hidden: true,
    group: "Sequence Feature",
    facet: true,
    facet_hidden: false,
    search: false,
  },
  subtype: {
    label: "Subtype",
    field: "subtype",
    hidden: true,
    group: "Sequence Feature",
    facet: true,
    facet_hidden: false,
    search: false,
  },
  comments: {
    label: "Comments",
    field: "comments",
    hidden: true,
    group: "Sequence Feature",
    facet: false,
    facet_hidden: true,
    search: false,
  },
} satisfies DataFieldMap;
