name: Lint Verification

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
      - test
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint
